Repository apple/swift-http-structured-headers, pull requests merged in 2022-04, with the labels that each got.

#19 Drop support for Swift 5.2 and 5.3
  .swiftformat
  Package.swift
  docker/Dockerfile
  docker/docker-compose.1604.52.yaml
  docker/docker-compose.1804.53.yaml
  docker/docker-compose.1804.54.yaml
  docker/docker-compose.2004.54.yaml
Labels: 🔼 needs-minor-version-bump

#21 Fix warnings, that appeared after requiring Swift 5.4
  Package.swift
Labels: needs-no-version-bump

#22 Remove redundant conformance constraints
  Sources/RawStructuredFieldValues/OrderedMap.swift
Labels: patch-version-bump-only
